#include <Rcpp.h>
#include "BinnedVector.hpp"
#include "summary.hpp"
using namespace Rcpp;

template<typename Stat>
List condense_1d(const NumericVector& x, const NumericVector& z,
                 const NumericVector& w, double origin, double binwidth,
                 const Stat& stat) {

  BinnedVector group(x, origin, binwidth);
  int n_obs = group.size();
  int n_bins = group.nbins();

  const NumericVector& weight_ = (w.size() > 0) ? w :
    rep(NumericVector::create(1), n_obs);
  const NumericVector& z_ = (z.size() > 0) ? z :
    rep(NumericVector::create(1), n_obs);

  // Push values into stats
  std::vector<Stat> stats(n_bins, stat);
  for(int i = 0; i < n_obs; ++i) {
    int bin = group.bin_i(i);
    // Rcout << "i: " << i << " bin: " << bin << "\n";
    stats.at(bin).push(z_[i], weight_[i]);
  }

  // Compute values from stats and determine bins
  int n_stats = stat.size();
  NumericVector bin(n_bins);
  NumericMatrix out(n_bins, n_stats);

  for (int i = 0; i < n_bins; ++i) {
    bin[i] = group.unbin(i);

    for (int j = 0; j < n_stats; ++j) {
      out(i, j) = stats[i].compute(j);
    }
  }

  // Name output columns
  CharacterVector out_cols(n_stats);
  for (int j = 0; j < n_stats; ++j) {
    out_cols[j] = stat.name(j);
  }
  out.attr("dimnames") = List::create(CharacterVector::create(), out_cols);

  return List::create(bin, out);
}

// -----------------------------------------------------------------------------
// Autogenerated by condense-gen.r
//
//// [[Rcpp::export]]
//List condense_count(const List& x, const NumericVector& z,
//                       const NumericVector& weight, bool drop = false) {
//  if (drop) {
//    return sparse_condense(BinnedVectors(x), z, weight, SummarySum(0));
//  } else {
//    return condense(BinnedVectors(x), z, weight, SummarySum(0));
//  }
//}
//
//// [[Rcpp::export]]
//List condense_sum(const List& x, const NumericVector& z,
//                       const NumericVector& weight, bool drop = false) {
//  if (drop) {
//    return sparse_condense(BinnedVectors(x), z, weight, SummarySum(1));
//  } else {
//    return condense(BinnedVectors(x), z, weight, SummarySum(1));
//  }
//}
//
//// [[Rcpp::export]]
//List condense_mean(const List& x, const NumericVector& z,
//                       const NumericVector& weight, bool drop = false) {
//  if (drop) {
//    return sparse_condense(BinnedVectors(x), z, weight, SummaryMoments(1));
//  } else {
//    return condense(BinnedVectors(x), z, weight, SummaryMoments(1));
//  }
//}
//
//// [[Rcpp::export]]
//List condense_sd(const List& x, const NumericVector& z,
//                       const NumericVector& weight, bool drop = false) {
//  if (drop) {
//    return sparse_condense(BinnedVectors(x), z, weight, SummaryMoments(2));
//  } else {
//    return condense(BinnedVectors(x), z, weight, SummaryMoments(2));
//  }
//}
//
//// [[Rcpp::export]]
//List condense_median(const List& x, const NumericVector& z,
//                       const NumericVector& weight, bool drop = false) {
//  if (drop) {
//    return sparse_condense(BinnedVectors(x), z, weight, SummaryMedian());
//  } else {
//    return condense(BinnedVectors(x), z, weight, SummaryMedian());
//  }
//}
