# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Efficient implementation of range.
#'
#' This is an efficient C++ implementation of range for numeric vectors:
#' it avoids S3 dispatch, and computes both min and max in a single pass
#' through the input.
#'
#' @param x a numeric vector, or a \code{\link{ranged}} object
#' @param finite If \code{TRUE} ignores missing values and infinities. Note
#'   that if the vector is empty, or only contains missing values,
#'   \code{frange} will return \code{c(Inf, -Inf)} because those are the
#'   identity values for \code{\link{min}} and \code{\link{max}} respectively.
#' @export
#' @examples
#' x <- runif(1e6)
#' system.time(range(x))
#' system.time(frange(x))
frange <- function(x, finite = TRUE) {
    .Call('ggvis_frange', PACKAGE = 'ggvis', x, finite)
}

bisquare <- function(u, b) {
    .Call('ggvis_bisquare', PACKAGE = 'ggvis', u, b)
}

regress <- function(x, y, w) {
    .Call('ggvis_regress', PACKAGE = 'ggvis', x, y, w)
}

medianC <- function(x) {
    .Call('ggvis_median', PACKAGE = 'ggvis', x)
}

regress_robust <- function(x, y, w, iterations = 3L) {
    .Call('ggvis_regress_robust', PACKAGE = 'ggvis', x, y, w, iterations)
}

compute_moments <- function(x) {
    .Call('ggvis_compute_moments', PACKAGE = 'ggvis', x)
}

compute_sum <- function(x) {
    .Call('ggvis_compute_sum', PACKAGE = 'ggvis', x)
}

compute_median <- function(x) {
    .Call('ggvis_compute_median', PACKAGE = 'ggvis', x)
}

